/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyTeamRouteImport } from './routes/my-team'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as TeamRegistrationRouteImport } from './routes/team-registration'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTeamRoute = MyTeamRouteImport.update({
  id: '/my-team',
  path: '/my-team',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRegistrationRoute = TeamRegistrationRouteImport.update({
  id: '/team-registration',
  path: '/team-registration',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-team': typeof MyTeamRoute
  '/problems': typeof ProblemsRoute
  '/team-registration': typeof TeamRegistrationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-team': typeof MyTeamRoute
  '/problems': typeof ProblemsRoute
  '/team-registration': typeof TeamRegistrationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-team': typeof MyTeamRoute
  '/problems': typeof ProblemsRoute
  '/team-registration': typeof TeamRegistrationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/my-team' | '/problems' | '/team-registration'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/my-team' | '/problems' | '/team-registration'
  id: '__root__' | '/' | '/my-team' | '/problems' | '/team-registration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyTeamRoute: typeof MyTeamRoute
  ProblemsRoute: typeof ProblemsRoute
  TeamRegistrationRoute: typeof TeamRegistrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-team': {
      id: '/my-team'
      path: '/my-team'
      fullPath: '/my-team'
      preLoaderRoute: typeof MyTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-registration': {
      id: '/team-registration'
      path: '/team-registration'
      fullPath: '/team-registration'
      preLoaderRoute: typeof TeamRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyTeamRoute: MyTeamRoute,
  ProblemsRoute: ProblemsRoute,
  TeamRegistrationRoute: TeamRegistrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
