/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAnalyzerRouteImport } from './routes/_authenticated/analyzer'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDeadlinesRouteImport } from './routes/_authenticated/deadlines'
import { Route as AuthenticatedMyTeamRouteImport } from './routes/_authenticated/my-team'
import { Route as AuthenticatedProblemsRouteImport } from './routes/_authenticated/problems'
import { Route as AuthenticatedProposalRouteImport } from './routes/_authenticated/proposal'
import { Route as AuthenticatedRecommendationsRouteImport } from './routes/_authenticated/recommendations'
import { Route as AuthenticatedRepositoryRouteImport } from './routes/_authenticated/repository'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated/results'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSimilarityRouteImport } from './routes/_authenticated/similarity'
import { Route as AuthenticatedTeamRegistrationRouteImport } from './routes/_authenticated/team-registration'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyzerRoute = AuthenticatedAnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeadlinesRoute = AuthenticatedDeadlinesRouteImport.update({
  id: '/deadlines',
  path: '/deadlines',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyTeamRoute = AuthenticatedMyTeamRouteImport.update({
  id: '/my-team',
  path: '/my-team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProblemsRoute = AuthenticatedProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProposalRoute = AuthenticatedProposalRouteImport.update({
  id: '/proposal',
  path: '/proposal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecommendationsRoute =
  AuthenticatedRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRepositoryRoute = AuthenticatedRepositoryRouteImport.update({
  id: '/repository',
  path: '/repository',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSimilarityRoute = AuthenticatedSimilarityRouteImport.update({
  id: '/similarity',
  path: '/similarity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRegistrationRoute =
  AuthenticatedTeamRegistrationRouteImport.update({
    id: '/team-registration',
    path: '/team-registration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/analyzer': typeof AuthenticatedAnalyzerRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deadlines': typeof AuthenticatedDeadlinesRoute
  '/my-team': typeof AuthenticatedMyTeamRoute
  '/problems': typeof AuthenticatedProblemsRoute
  '/proposal': typeof AuthenticatedProposalRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/repository': typeof AuthenticatedRepositoryRoute
  '/results': typeof AuthenticatedResultsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/similarity': typeof AuthenticatedSimilarityRoute
  '/team-registration': typeof AuthenticatedTeamRegistrationRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyzer': typeof AuthenticatedAnalyzerRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deadlines': typeof AuthenticatedDeadlinesRoute
  '/my-team': typeof AuthenticatedMyTeamRoute
  '/problems': typeof AuthenticatedProblemsRoute
  '/proposal': typeof AuthenticatedProposalRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/repository': typeof AuthenticatedRepositoryRoute
  '/results': typeof AuthenticatedResultsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/similarity': typeof AuthenticatedSimilarityRoute
  '/team-registration': typeof AuthenticatedTeamRegistrationRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/analyzer': typeof AuthenticatedAnalyzerRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deadlines': typeof AuthenticatedDeadlinesRoute
  '/_authenticated/my-team': typeof AuthenticatedMyTeamRoute
  '/_authenticated/problems': typeof AuthenticatedProblemsRoute
  '/_authenticated/proposal': typeof AuthenticatedProposalRoute
  '/_authenticated/recommendations': typeof AuthenticatedRecommendationsRoute
  '/_authenticated/repository': typeof AuthenticatedRepositoryRoute
  '/_authenticated/results': typeof AuthenticatedResultsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/similarity': typeof AuthenticatedSimilarityRoute
  '/_authenticated/team-registration': typeof AuthenticatedTeamRegistrationRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analyzer'
    | '/announcements'
    | '/dashboard'
    | '/deadlines'
    | '/my-team'
    | '/problems'
    | '/proposal'
    | '/recommendations'
    | '/repository'
    | '/results'
    | '/settings'
    | '/similarity'
    | '/team-registration'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyzer'
    | '/announcements'
    | '/dashboard'
    | '/deadlines'
    | '/my-team'
    | '/problems'
    | '/proposal'
    | '/recommendations'
    | '/repository'
    | '/results'
    | '/settings'
    | '/similarity'
    | '/team-registration'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/analyzer'
    | '/_authenticated/announcements'
    | '/_authenticated/dashboard'
    | '/_authenticated/deadlines'
    | '/_authenticated/my-team'
    | '/_authenticated/problems'
    | '/_authenticated/proposal'
    | '/_authenticated/recommendations'
    | '/_authenticated/repository'
    | '/_authenticated/results'
    | '/_authenticated/settings'
    | '/_authenticated/similarity'
    | '/_authenticated/team-registration'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analyzer': {
      id: '/_authenticated/analyzer'
      path: '/analyzer'
      fullPath: '/analyzer'
      preLoaderRoute: typeof AuthenticatedAnalyzerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deadlines': {
      id: '/_authenticated/deadlines'
      path: '/deadlines'
      fullPath: '/deadlines'
      preLoaderRoute: typeof AuthenticatedDeadlinesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-team': {
      id: '/_authenticated/my-team'
      path: '/my-team'
      fullPath: '/my-team'
      preLoaderRoute: typeof AuthenticatedMyTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/problems': {
      id: '/_authenticated/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof AuthenticatedProblemsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposal': {
      id: '/_authenticated/proposal'
      path: '/proposal'
      fullPath: '/proposal'
      preLoaderRoute: typeof AuthenticatedProposalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recommendations': {
      id: '/_authenticated/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AuthenticatedRecommendationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repository': {
      id: '/_authenticated/repository'
      path: '/repository'
      fullPath: '/repository'
      preLoaderRoute: typeof AuthenticatedRepositoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/similarity': {
      id: '/_authenticated/similarity'
      path: '/similarity'
      fullPath: '/similarity'
      preLoaderRoute: typeof AuthenticatedSimilarityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team-registration': {
      id: '/_authenticated/team-registration'
      path: '/team-registration'
      fullPath: '/team-registration'
      preLoaderRoute: typeof AuthenticatedTeamRegistrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAnalyzerRoute: typeof AuthenticatedAnalyzerRoute
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeadlinesRoute: typeof AuthenticatedDeadlinesRoute
  AuthenticatedMyTeamRoute: typeof AuthenticatedMyTeamRoute
  AuthenticatedProblemsRoute: typeof AuthenticatedProblemsRoute
  AuthenticatedProposalRoute: typeof AuthenticatedProposalRoute
  AuthenticatedRecommendationsRoute: typeof AuthenticatedRecommendationsRoute
  AuthenticatedRepositoryRoute: typeof AuthenticatedRepositoryRoute
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSimilarityRoute: typeof AuthenticatedSimilarityRoute
  AuthenticatedTeamRegistrationRoute: typeof AuthenticatedTeamRegistrationRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAnalyzerRoute: AuthenticatedAnalyzerRoute,
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeadlinesRoute: AuthenticatedDeadlinesRoute,
  AuthenticatedMyTeamRoute: AuthenticatedMyTeamRoute,
  AuthenticatedProblemsRoute: AuthenticatedProblemsRoute,
  AuthenticatedProposalRoute: AuthenticatedProposalRoute,
  AuthenticatedRecommendationsRoute: AuthenticatedRecommendationsRoute,
  AuthenticatedRepositoryRoute: AuthenticatedRepositoryRoute,
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSimilarityRoute: AuthenticatedSimilarityRoute,
  AuthenticatedTeamRegistrationRoute: AuthenticatedTeamRegistrationRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
